fix: add '--' to checkout command to avoid ambiguity
peter-evans/create-pull-request pull request #1051
Opened 2022-01-29 08:41 UTC by kenji-miyake

Hi, thank you for developing this tool!

I found it causes an error when there are a branch and a path with the same name.
As explained [here](https://github.com/git/git/commit/a047fafc7866cc4087201e284dc1f53e8f9a32d5), adding `--` can fix this problem.

I've tested this here.
Before: https://github.com/kenji-miyake/autoware-github-actions/pull/11
After: https://github.com/kenji-miyake/autoware-github-actions/pull/12

I came up with using `git switch` as another option, but I refrained from that because it could be a big change.

2022-01-30 00:49 UTC, peter-evans requested changes
Thank you for this contribution!

I think the format check is failing because of the semicolon. Let's get the formatting fixed and I'll run the test suite.

2022-01-30 00:49 UTC, peter-evans commented on src/git-command-manager.ts
> +    args.push('--');
```suggestion
    args.push('--')
```

2022-01-30 13:16 UTC, kenji-miyake commented on src/git-command-manager.ts
> +    args.push('--');
Oh, I'm sorry, thank you!

2022-01-31 00:34 UTC, peter-evans commented
/test repository=kenji-miyake/create-pull-request branch=fix-ambiguity-between-branch-and-path

2022-01-31 00:48 UTC, peter-evans approved these changes
👍

2022-01-31 00:50 UTC, merged

2022-01-31 00:59 UTC, peter-evans commented
Thank you again for this fix! 🏅 

Released as `v3.12.1` / `v3`